# Generated by Django 2.1.8 on 2019-08-05 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freeBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_blog',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
