# Generated by Django 2.1.8 on 2019-07-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b_blog',
            name='follow',
        ),
    ]
