# Generated by Django 2.1.8 on 2019-08-06 06:23

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freeBoard', '0002_b_blog_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_blog',
            name='attached_file',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to='attached_file/'),
        ),
        migrations.AddField(
            model_name='b_blog',
            name='attached_img',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to='attached_img/'),
        ),
    ]
