# Generated by Django 2.1.8 on 2019-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeBoard', '0003_b_blog_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b_blog',
            name='count',
        ),
        migrations.AddField(
            model_name='b_blog',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
