# Generated by Django 2.1.8 on 2019-07-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeBoard', '0004_auto_20190718_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b_blog',
            name='count',
        ),
    ]
