# Generated by Django 2.1.8 on 2019-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('freeBoard', '0005_remove_b_blog_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_blog',
            name='hashtag',
            field=models.ManyToManyField(related_name='freeboard_tag', to='hashtag.Hashtag'),
        ),
    ]
