# Generated by Django 2.1.8 on 2019-07-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view_request', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='view_request.Blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
