# Generated by Django 2.1.8 on 2019-07-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_request', '0002_blog_user'),
        ('view_request', '0003_auto_20190712_2028'),
    ]

    operations = [
    ]
