# Generated by Django 2.1.8 on 2019-07-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_notifi_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('mission_application', 'Mission_application'), ('chat', 'Chat')], max_length=20),
        ),
    ]
