# Generated by Django 2.1.8 on 2019-08-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_submit_form_attachment'),
        ('notification', '0006_auto_20190730_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notifi_post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifi_post', to='request.Post'),
        ),
    ]
