# Generated by Django 2.1.8 on 2019-08-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20190802_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
