# Generated by Django 2.1.8 on 2019-08-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_notification_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notifi_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
