# Generated by Django 2.1.8 on 2019-08-09 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Date published')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField(null=True)),
                ('complainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainer', to='accounts.Profile')),
                ('prey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prey', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='MTM_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_fk', to='accounts.Profile')),
                ('request_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_fk', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField(null=True)),
                ('ratings', models.IntegerField(default=0)),
                ('writer', models.CharField(max_length=200, null=True)),
                ('review_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='chatting',
            name='chatting_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.MTM_chat'),
        ),
    ]
