# Generated by Django 2.1.8 on 2019-07-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20190712_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
