# Generated by Django 2.1.8 on 2019-07-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='writer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
