# Generated by Django 2.1.8 on 2019-07-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        ('accounts', '0001_initial'),
        ('mypage', '0003_auto_20190718_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTM_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Post')),
                ('profile_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
