# Generated by Django 2.1.8 on 2019-07-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20190730_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
