# Generated by Django 2.1.8 on 2019-07-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_mtm_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
