# Generated by Django 2.1.8 on 2019-07-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_average_ratings'),
        ('mypage', '0005_auto_20190730_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField(null=True)),
                ('complainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainer', to='accounts.Profile')),
                ('prey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prey', to='accounts.Profile')),
            ],
        ),
    ]
