# Generated by Django 2.1.8 on 2019-07-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_chatting'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtm_chat',
            name='chat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.Chatting'),
        ),
    ]
