# Generated by Django 2.1.8 on 2019-07-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mypage', '0006_mtm_chat_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtm_chat',
            name='post_fk',
        ),
        migrations.AddField(
            model_name='mtm_chat',
            name='request_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_fk', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='mtm_chat',
            name='profile_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_fk', to='accounts.Profile'),
        ),
    ]
