# Generated by Django 2.1.8 on 2019-07-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_auto_20190725_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtm_chat',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='chatting',
            name='chatting_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.MTM_chat'),
        ),
    ]
