# Generated by Django 2.1.8 on 2019-08-09 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='default_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_img', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='tmp_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('introduction', models.TextField(null=True)),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('approval', models.BooleanField(default=False)),
                ('profile_id', models.CharField(max_length=200, null=True, unique=True)),
                ('profile_img', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='profile_img/')),
                ('money', models.IntegerField(default=0)),
                ('connector', models.IntegerField(null=True)),
                ('mission_count', models.IntegerField(default=0)),
                ('hashtag', models.ManyToManyField(related_name='my_tag', to='hashtag.Hashtag')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
