# Generated by Django 2.1.8 on 2019-07-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190718_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
