# Generated by Django 2.1.8 on 2019-07-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190727_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='connector',
        ),
    ]
