# Generated by Django 2.1.8 on 2019-07-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190718_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ssn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
