# Generated by Django 2.1.8 on 2019-07-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connector',
            field=models.IntegerField(null=True),
        ),
    ]
