# Generated by Django 2.1.8 on 2019-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190718_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='hashtag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
