# Generated by Django 2.1.8 on 2019-07-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mission_count',
            field=models.IntegerField(default=0),
        ),
    ]
