# Generated by Django 2.1.8 on 2019-07-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_mission_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
