# Generated by Django 2.1.8 on 2019-07-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_post_mypage'),
        ('accounts', '0006_auto_20190722_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applyMission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Post'),
        ),
    ]
