# Generated by Django 2.1.8 on 2019-07-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_average_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='average_ratings',
        ),
    ]
