# Generated by Django 2.1.8 on 2019-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_average_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
