# Generated by Django 2.1.8 on 2019-08-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190805_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ssn',
        ),
    ]
