# Generated by Django 2.1.8 on 2019-07-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_connector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hashtag',
        ),
    ]
