# Generated by Django 2.1.8 on 2019-08-06 07:12

from django.db import migrations, models
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_ssn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_img', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='tmp_img/')),
            ],
        ),
    ]
