# Generated by Django 2.1.8 on 2019-08-08 12:26

from django.db import migrations, models
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='default_img/')),
            ],
        ),
    ]
