# Generated by Django 2.1.8 on 2019-07-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('accounts', '0012_remove_profile_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hashtag',
            field=models.ManyToManyField(related_name='my_tag', to='hashtag.Hashtag'),
        ),
    ]
