# Generated by Django 2.1.8 on 2019-07-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
