# Generated by Django 2.1.8 on 2019-07-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0030_auto_20190724_1112'),
        ('accounts', '0014_profile_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Post'),
        ),
    ]
