# Generated by Django 2.1.8 on 2019-07-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
                ('announcement_img', models.ImageField(blank=True, null=True, upload_to='announcement_img/')),
                ('announcement_file', models.FileField(blank=True, null=True, upload_to='announcement_file/')),
            ],
        ),
    ]
