# Generated by Django 2.1.8 on 2019-08-09 10:19

from django.db import migrations, models
import django_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('writer', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('announcement_img', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='announcement_img/')),
                ('announcement_file', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='announcement_file/')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Date published')),
            ],
        ),
    ]
