# Generated by Django 2.1.8 on 2019-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='writer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
