# Generated by Django 2.1.8 on 2019-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190730_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date published'),
        ),
    ]
