# Generated by Django 2.1.8 on 2019-07-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_announcement_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_file',
            field=models.FileField(blank=True, default='...', null=True, upload_to='announcement_file/'),
        ),
    ]
