# Generated by Django 2.1.8 on 2019-07-30 13:27

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190730_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_img',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to='announcement_img/'),
        ),
    ]
