# Generated by Django 2.1.8 on 2019-07-30 13:37

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190730_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_file',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to='announcement_file/'),
        ),
    ]
