# Generated by Django 2.1.8 on 2019-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
    ]
