# Generated by Django 2.1.8 on 2019-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attached_img',
            field=models.ImageField(blank=True, default='attached_img/default.jpg', null=True, upload_to='attached_img/'),
        ),
    ]
