# Generated by Django 2.1.8 on 2019-07-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_post_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='attached_file/'),
        ),
    ]
