# Generated by Django 2.1.8 on 2019-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_post_attached_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attached_img',
            field=models.ImageField(blank=True, null=True, upload_to='attached_img/'),
        ),
    ]
