# Generated by Django 2.1.8 on 2019-07-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20190718_2320'),
        ('request', '0003_remove_post_con'),
    ]

    operations = [
    ]
