# Generated by Django 2.1.8 on 2019-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_post_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_form',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='submit_file/'),
        ),
    ]
