# Generated by Django 2.1.8 on 2019-07-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_merge_20190718_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
