# Generated by Django 2.1.8 on 2019-07-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_comment_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
