# Generated by Django 2.1.8 on 2019-08-07 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20190805_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='scrapped', to=settings.AUTH_USER_MODEL),
        ),
    ]
