# Generated by Django 2.1.8 on 2019-07-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20190720_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(related_name='tag', to='request.Hashtag'),
        ),
    ]
