# Generated by Django 2.1.8 on 2019-07-22 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0009_auto_20190722_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mypage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mypage', to=settings.AUTH_USER_MODEL),
        ),
    ]
