# Generated by Django 2.1.8 on 2019-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_post_mypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applier',
            field=models.TextField(null=True),
        ),
    ]
