# Generated by Django 2.1.8 on 2019-07-22 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0012_remove_post_applier'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applyMission',
            field=models.ManyToManyField(blank=True, related_name='applyMission', to=settings.AUTH_USER_MODEL),
        ),
    ]
