# Generated by Django 2.1.8 on 2019-07-23 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0013_post_applymission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='applyMission',
        ),
        migrations.AddField(
            model_name='applymission',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Post'),
        ),
        migrations.AddField(
            model_name='applymission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
