# Generated by Django 2.1.8 on 2019-07-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_auto_20190723_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mypage',
        ),
    ]
