# Generated by Django 2.1.8 on 2019-07-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_remove_post_mypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
