# Generated by Django 2.1.8 on 2019-07-23 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0017_auto_20190723_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymission',
            name='applier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applier', to=settings.AUTH_USER_MODEL),
        ),
    ]
