# Generated by Django 2.1.8 on 2019-07-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_applymission_applier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymission',
            name='applier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applier', to='accounts.Profile'),
        ),
    ]
