# Generated by Django 2.1.8 on 2019-07-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_auto_20190723_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymission',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Post'),
        ),
    ]
