# Generated by Django 2.1.8 on 2019-07-23 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_auto_20190723_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
