# Generated by Django 2.1.8 on 2019-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0022_auto_20190723_0642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(related_name='tag', to='hashtag.Hashtag'),
        ),
    ]
