# Generated by Django 2.1.8 on 2019-07-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_auto_20190724_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(related_name='post_tag', to='hashtag.Hashtag'),
        ),
    ]
