# Generated by Django 2.1.8 on 2019-07-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_auto_20190724_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_id',
            field=models.IntegerField(null=True),
        ),
    ]
