# Generated by Django 2.1.8 on 2019-07-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_post_approved_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approved_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
