# Generated by Django 2.1.8 on 2019-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0026_auto_20190724_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='submit_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('writer', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Date published')),
                ('body', models.TextField(null=True)),
                ('s_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
