# Generated by Django 2.1.8 on 2019-07-24 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0027_submit_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_form',
            name='submit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Post'),
        ),
    ]
