# Generated by Django 2.1.8 on 2019-07-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_submit_form_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit_form',
            name='s_flag',
        ),
        migrations.AddField(
            model_name='post',
            name='s_flag',
            field=models.BooleanField(default=False),
        ),
    ]
