# Generated by Django 2.1.8 on 2019-07-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0029_auto_20190724_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='o_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='o_writer',
            new_name='writer',
        ),
    ]
